<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\AllahName;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\DB;

class AllahNameSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('allah_names')->truncate();

        $names = [
            [
                'number' => 1,
                'arabic' => 'الرَّحْمَنُ',
                'transliteration' => 'Ar-Rahman',
                'meaning_english' => 'The All-Compassionate',
                'meaning_urdu' => 'نہایت مہربان',
                'benefits' => 'Reciting this name brings immense spiritual benefits and closeness to Allah.',
                'slug' => Str::slug('Ar-Rahman'),
            ],
            [
                'number' => 2,
                'arabic' => 'الرَّحِيمُ',
                'transliteration' => 'Ar-Rahim',
                'meaning_english' => 'The All-Merciful',
                'meaning_urdu' => 'بڑا رحم کرنے والا',
                'benefits' => 'Reciting this name brings immense spiritual benefits and closeness to Allah.',
                'slug' => Str::slug('Ar-Rahim'),
            ],
            [
                'number' => 3,
                'arabic' => 'الْمَلِكُ',
                'transliteration' => 'Al-Malik',
                'meaning_english' => 'The Absolute Ruler',
                'meaning_urdu' => 'بادشاہ',
                'benefits' => 'Reciting this name brings immense spiritual benefits and closeness to Allah.',
                'slug' => Str::slug('Al-Malik'),
            ],
            [
                'number' => 4,
                'arabic' => 'الْقُدُّوسُ',
                'transliteration' => 'Al-Quddus',
                'meaning_english' => 'The Pure One',
                'meaning_urdu' => 'پاک ذات',
                'benefits' => 'Reciting this name brings immense spiritual benefits and closeness to Allah.',
                'slug' => Str::slug('Al-Quddus'),
            ],
            [
                'number' => 5,
                'arabic' => 'السَّلَامُ',
                'transliteration' => 'As-Salam',
                'meaning_english' => 'The Source of Peace',
                'meaning_urdu' => 'سلامتی دینے والا',
                'benefits' => 'Reciting this name brings immense spiritual benefits and closeness to Allah.',
                'slug' => Str::slug('As-Salam'),
            ],
            [
                'number' => 6,
                'arabic' => 'الْمُؤْمِنُ',
                'transliteration' => 'Al-Mu\'min',
                'meaning_english' => 'The Inspirer of Faith',
                'meaning_urdu' => 'امن دینے والا',
                'benefits' => 'Reciting this name brings immense spiritual benefits and closeness to Allah.',
                'slug' => Str::slug('Al-Mu\'min'),
            ],
            [
                'number' => 7,
                'arabic' => 'الْمُهَيْمِنُ',
                'transliteration' => 'Al-Muhaymin',
                'meaning_english' => 'The Guardian',
                'meaning_urdu' => 'نگہبان',
                'benefits' => 'Reciting this name brings immense spiritual benefits and closeness to Allah.',
                'slug' => Str::slug('Al-Muhaymin'),
            ],
            [
                'number' => 8,
                'arabic' => 'الْعَزِيزُ',
                'transliteration' => 'Al-Aziz',
                'meaning_english' => 'The Victorious',
                'meaning_urdu' => 'غالب',
                'benefits' => 'Reciting this name brings immense spiritual benefits and closeness to Allah.',
                'slug' => Str::slug('Al-Aziz'),
            ],
            [
                'number' => 9,
                'arabic' => 'الْجَبَّارُ',
                'transliteration' => 'Al-Jabbar',
                'meaning_english' => 'The Compeller',
                'meaning_urdu' => 'زبردست',
                'benefits' => 'Reciting this name brings immense spiritual benefits and closeness to Allah.',
                'slug' => Str::slug('Al-Jabbar'),
            ],
            [
                'number' => 10,
                'arabic' => 'الْمُتَكَبِّرُ',
                'transliteration' => 'Al-Mutakabbir',
                'meaning_english' => 'The Greatest',
                'meaning_urdu' => 'بڑائی والا',
                'benefits' => 'Reciting this name brings immense spiritual benefits and closeness to Allah.',
                'slug' => Str::slug('Al-Mutakabbir'),
            ],
            [
                'number' => 11,
                'arabic' => 'الْخَالِقُ',
                'transliteration' => 'Al-Khaliq',
                'meaning_english' => 'The Creator',
                'meaning_urdu' => 'پیدا کرنے والا',
                'benefits' => 'Reciting this name brings immense spiritual benefits and closeness to Allah.',
                'slug' => Str::slug('Al-Khaliq'),
            ],
            [
                'number' => 12,
                'arabic' => 'الْبَارِئُ',
                'transliteration' => 'Al-Bari\'',
                'meaning_english' => 'The Maker of Order',
                'meaning_urdu' => 'جان ڈالنے والا',
                'benefits' => 'Reciting this name brings immense spiritual benefits and closeness to Allah.',
                'slug' => Str::slug('Al-Bari\''),
            ],
            [
                'number' => 13,
                'arabic' => 'الْمُصَوِّرُ',
                'transliteration' => 'Al-Musawwir',
                'meaning_english' => 'The Shaper of Beauty',
                'meaning_urdu' => 'صورت بنانے والا',
                'benefits' => 'Reciting this name brings immense spiritual benefits and closeness to Allah.',
                'slug' => Str::slug('Al-Musawwir'),
            ],
            [
                'number' => 14,
                'arabic' => 'الْغَفَّارُ',
                'transliteration' => 'Al-Ghaffar',
                'meaning_english' => 'The Forgiving',
                'meaning_urdu' => 'بڑا بخشنے والا',
                'benefits' => 'Reciting this name brings immense spiritual benefits and closeness to Allah.',
                'slug' => Str::slug('Al-Ghaffar'),
            ],
            [
                'number' => 15,
                'arabic' => 'الْقَهَّارُ',
                'transliteration' => 'Al-Qahhar',
                'meaning_english' => 'The Subduer',
                'meaning_urdu' => 'سب پر غالب',
                'benefits' => 'Reciting this name brings immense spiritual benefits and closeness to Allah.',
                'slug' => Str::slug('Al-Qahhar'),
            ],
            [
                'number' => 16,
                'arabic' => 'الْوَهَّابُ',
                'transliteration' => 'Al-Wahhab',
                'meaning_english' => 'The Giver of All',
                'meaning_urdu' => 'بہت دینے والا',
                'benefits' => 'Reciting this name brings immense spiritual benefits and closeness to Allah.',
                'slug' => Str::slug('Al-Wahhab'),
            ],
            [
                'number' => 17,
                'arabic' => 'الرَّزَّاقُ',
                'transliteration' => 'Ar-Razzaq',
                'meaning_english' => 'The Sustainer',
                'meaning_urdu' => 'رزق دینے والا',
                'benefits' => 'Reciting this name brings immense spiritual benefits and closeness to Allah.',
                'slug' => Str::slug('Ar-Razzaq'),
            ],
            [
                'number' => 18,
                'arabic' => 'الْفَتَّاحُ',
                'transliteration' => 'Al-Fattah',
                'meaning_english' => 'The Opener',
                'meaning_urdu' => 'مشکلات حل کرنے والا',
                'benefits' => 'Reciting this name brings immense spiritual benefits and closeness to Allah.',
                'slug' => Str::slug('Al-Fattah'),
            ],
            [
                'number' => 19,
                'arabic' => 'اَلْعَلِيْمُ',
                'transliteration' => 'Al-\'Alim',
                'meaning_english' => 'The Knower of All',
                'meaning_urdu' => 'سب کچھ جاننے والا',
                'benefits' => 'Reciting this name brings immense spiritual benefits and closeness to Allah.',
                'slug' => Str::slug('Al-\'Alim'),
            ],
            [
                'number' => 20,
                'arabic' => 'الْقَابِضُ',
                'transliteration' => 'Al-Qabid',
                'meaning_english' => 'The Constrictor',
                'meaning_urdu' => 'روزی تنگ کرنے والا',
                'benefits' => 'Reciting this name brings immense spiritual benefits and closeness to Allah.',
                'slug' => Str::slug('Al-Qabid'),
            ],
            [
                'number' => 21,
                'arabic' => 'الْبَاسِطُ',
                'transliteration' => 'Al-Basit',
                'meaning_english' => 'The Reliever',
                'meaning_urdu' => 'روزی کشادہ کرنے والا',
                'benefits' => 'Reciting this name brings immense spiritual benefits and closeness to Allah.',
                'slug' => Str::slug('Al-Basit'),
            ],
            [
                'number' => 22,
                'arabic' => 'الْخَافِضُ',
                'transliteration' => 'Al-Khafid',
                'meaning_english' => 'The Abaser',
                'meaning_urdu' => 'پست کرنے والا',
                'benefits' => 'Reciting this name brings immense spiritual benefits and closeness to Allah.',
                'slug' => Str::slug('Al-Khafid'),
            ],
            [
                'number' => 23,
                'arabic' => 'الرَّافِعُ',
                'transliteration' => 'Ar-Rafi',
                'meaning_english' => 'The Exalter',
                'meaning_urdu' => 'بلند کرنے والا',
                'benefits' => 'Reciting this name brings immense spiritual benefits and closeness to Allah.',
                'slug' => Str::slug('Ar-Rafi'),
            ],
            [
                'number' => 24,
                'arabic' => 'الْمُعِزُّ',
                'transliteration' => 'Al-Mu\'izz',
                'meaning_english' => 'The Bestower of Honors',
                'meaning_urdu' => 'عزت دینے والا',
                'benefits' => 'Reciting this name brings immense spiritual benefits and closeness to Allah.',
                'slug' => Str::slug('Al-Mu\'izz'),
            ],
            [
                'number' => 25,
                'arabic' => 'المُذِلُّ',
                'transliteration' => 'Al-Mudhill',
                'meaning_english' => 'The Humiliator',
                'meaning_urdu' => 'ذلت دینے والا',
                'benefits' => 'Reciting this name brings immense spiritual benefits and closeness to Allah.',
                'slug' => Str::slug('Al-Mudhill'),
            ],
            [
                'number' => 26,
                'arabic' => 'السَّمِيعُ',
                'transliteration' => 'As-Sami',
                'meaning_english' => 'The Hearer of All',
                'meaning_urdu' => 'سب کچھ سننے والا',
                'benefits' => 'Reciting this name brings immense spiritual benefits and closeness to Allah.',
                'slug' => Str::slug('As-Sami'),
            ],
            [
                'number' => 27,
                'arabic' => 'الْبَصِيرُ',
                'transliteration' => 'Al-Basir',
                'meaning_english' => 'The Seer of All',
                'meaning_urdu' => 'سب کچھ دیکھنے والا',
                'benefits' => 'Reciting this name brings immense spiritual benefits and closeness to Allah.',
                'slug' => Str::slug('Al-Basir'),
            ],
            [
                'number' => 28,
                'arabic' => 'الْحَكَمُ',
                'transliteration' => 'Al-Hakam',
                'meaning_english' => 'The Judge',
                'meaning_urdu' => 'فیصلہ کرنے والا',
                'benefits' => 'Reciting this name brings immense spiritual benefits and closeness to Allah.',
                'slug' => Str::slug('Al-Hakam'),
            ],
            [
                'number' => 29,
                'arabic' => 'الْعَدْلُ',
                'transliteration' => 'Al-\'Adl',
                'meaning_english' => 'The Just',
                'meaning_urdu' => 'انصاف کرنے والا',
                'benefits' => 'Reciting this name brings immense spiritual benefits and closeness to Allah.',
                'slug' => Str::slug('Al-\'Adl'),
            ],
            [
                'number' => 30,
                'arabic' => 'اللَّطِيفُ',
                'transliteration' => 'Al-Latif',
                'meaning_english' => 'The Subtle One',
                'meaning_urdu' => 'لطف و کرم کرنے والا',
                'benefits' => 'Reciting this name brings immense spiritual benefits and closeness to Allah.',
                'slug' => Str::slug('Al-Latif'),
            ],
            [
                'number' => 31,
                'arabic' => 'الْخَبِيرُ',
                'transliteration' => 'Al-Khabir',
                'meaning_english' => 'The All-Aware',
                'meaning_urdu' => 'خبردار',
                'benefits' => 'Reciting this name brings immense spiritual benefits and closeness to Allah.',
                'slug' => Str::slug('Al-Khabir'),
            ],
            [
                'number' => 32,
                'arabic' => 'الْحَلِيمُ',
                'transliteration' => 'Al-Halim',
                'meaning_english' => 'The Forbearing',
                'meaning_urdu' => 'بردبار',
                'benefits' => 'Reciting this name brings immense spiritual benefits and closeness to Allah.',
                'slug' => Str::slug('Al-Halim'),
            ],
            [
                'number' => 33,
                'arabic' => 'الْعَظِيمُ',
                'transliteration' => 'Al-\'Azim',
                'meaning_english' => 'The Magnificent',
                'meaning_urdu' => 'عظمت والا',
                'benefits' => 'Reciting this name brings immense spiritual benefits and closeness to Allah.',
                'slug' => Str::slug('Al-\'Azim'),
            ],
            [
                'number' => 34,
                'arabic' => 'الْغَفُورُ',
                'transliteration' => 'Al-Ghafur',
                'meaning_english' => 'The Forgiver and Hider of Faults',
                'meaning_urdu' => 'بخشنے والا',
                'benefits' => 'Reciting this name brings immense spiritual benefits and closeness to Allah.',
                'slug' => Str::slug('Al-Ghafur'),
            ],
            [
                'number' => 35,
                'arabic' => 'الشَّكُورُ',
                'transliteration' => 'Ash-Shakur',
                'meaning_english' => 'The Rewarder of Thankfulness',
                'meaning_urdu' => 'قدردان',
                'benefits' => 'Reciting this name brings immense spiritual benefits and closeness to Allah.',
                'slug' => Str::slug('Ash-Shakur'),
            ],
            [
                'number' => 36,
                'arabic' => 'الْعَلِيُّ',
                'transliteration' => 'Al-\'Ali',
                'meaning_english' => 'The Highest',
                'meaning_urdu' => 'سب سے بلند',
                'benefits' => 'Reciting this name brings immense spiritual benefits and closeness to Allah.',
                'slug' => Str::slug('Al-\'Ali'),
            ],
            [
                'number' => 37,
                'arabic' => 'الْكَبِيرُ',
                'transliteration' => 'Al-Kabir',
                'meaning_english' => 'The Greatest',
                'meaning_urdu' => 'سب سے بڑا',
                'benefits' => 'Reciting this name brings immense spiritual benefits and closeness to Allah.',
                'slug' => Str::slug('Al-Kabir'),
            ],
            [
                'number' => 38,
                'arabic' => 'الْحَفِيظُ',
                'transliteration' => 'Al-Hafiz',
                'meaning_english' => 'The Preserver',
                'meaning_urdu' => 'حفاظت کرنے والا',
                'benefits' => 'Reciting this name brings immense spiritual benefits and closeness to Allah.',
                'slug' => Str::slug('Al-Hafiz'),
            ],
            [
                'number' => 39,
                'arabic' => 'المُقيِت',
                'transliteration' => 'Al-Muqit',
                'meaning_english' => 'The Nourisher',
                'meaning_urdu' => 'روزی دینے والا',
                'benefits' => 'Reciting this name brings immense spiritual benefits and closeness to Allah.',
                'slug' => Str::slug('Al-Muqit'),
            ],
            [
                'number' => 40,
                'arabic' => 'الْحَسِيبُ',
                'transliteration' => 'Al-Hasib',
                'meaning_english' => 'The Accounter',
                'meaning_urdu' => 'حساب لینے والا',
                'benefits' => 'Reciting this name brings immense spiritual benefits and closeness to Allah.',
                'slug' => Str::slug('Al-Hasib'),
            ],
            [
                'number' => 41,
                'arabic' => 'الْجَلِيلُ',
                'transliteration' => 'Al-Jalil',
                'meaning_english' => 'The Mighty',
                'meaning_urdu' => 'بزرگی والا',
                'benefits' => 'Reciting this name brings immense spiritual benefits and closeness to Allah.',
                'slug' => Str::slug('Al-Jalil'),
            ],
            [
                'number' => 42,
                'arabic' => 'الْكَرِيمُ',
                'transliteration' => 'Al-Karim',
                'meaning_english' => 'The Generous',
                'meaning_urdu' => 'کرم کرنے والا',
                'benefits' => 'Reciting this name brings immense spiritual benefits and closeness to Allah.',
                'slug' => Str::slug('Al-Karim'),
            ],
            [
                'number' => 43,
                'arabic' => 'الرَّقِيبُ',
                'transliteration' => 'Ar-Raqib',
                'meaning_english' => 'The Watchful One',
                'meaning_urdu' => 'نگہبان',
                'benefits' => 'Reciting this name brings immense spiritual benefits and closeness to Allah.',
                'slug' => Str::slug('Ar-Raqib'),
            ],
            [
                'number' => 44,
                'arabic' => 'الْمُجِيبُ',
                'transliteration' => 'Al-Mujib',
                'meaning_english' => 'The Responder to Prayer',
                'meaning_urdu' => 'دعائیں قبول کرنے والا',
                'benefits' => 'Reciting this name brings immense spiritual benefits and closeness to Allah.',
                'slug' => Str::slug('Al-Mujib'),
            ],
            [
                'number' => 45,
                'arabic' => 'الْوَاسِعُ',
                'transliteration' => 'Al-Wasi',
                'meaning_english' => 'The All-Comprehending',
                'meaning_urdu' => 'وسعت والا',
                'benefits' => 'Reciting this name brings immense spiritual benefits and closeness to Allah.',
                'slug' => Str::slug('Al-Wasi'),
            ],
            [
                'number' => 46,
                'arabic' => 'الْحَكِيمُ',
                'transliteration' => 'Al-Hakim',
                'meaning_english' => 'The Perfectly Wise',
                'meaning_urdu' => 'حکمت والا',
                'benefits' => 'Reciting this name brings immense spiritual benefits and closeness to Allah.',
                'slug' => Str::slug('Al-Hakim'),
            ],
            [
                'number' => 47,
                'arabic' => 'الْوَدُودُ',
                'transliteration' => 'Al-Wadud',
                'meaning_english' => 'The Loving One',
                'meaning_urdu' => 'محبت کرنے والا',
                'benefits' => 'Reciting this name brings immense spiritual benefits and closeness to Allah.',
                'slug' => Str::slug('Al-Wadud'),
            ],
            [
                'number' => 48,
                'arabic' => 'الْمَجِيدُ',
                'transliteration' => 'Al-Majeed',
                'meaning_english' => 'The Majestic One',
                'meaning_urdu' => 'بزرگی والا',
                'benefits' => 'Reciting this name brings immense spiritual benefits and closeness to Allah.',
                'slug' => Str::slug('Al-Majeed'),
            ],
            [
                'number' => 49,
                'arabic' => 'الْبَاعِثُ',
                'transliteration' => 'Al-Ba\'ith',
                'meaning_english' => 'The Resurrector',
                'meaning_urdu' => 'اٹھانے والا',
                'benefits' => 'Reciting this name brings immense spiritual benefits and closeness to Allah.',
                'slug' => Str::slug('Al-Ba\'ith'),
            ],
            [
                'number' => 50,
                'arabic' => 'الشَّهِيدُ',
                'transliteration' => 'Ash-Shahid',
                'meaning_english' => 'The Witness',
                'meaning_urdu' => 'حاضر و ناظر',
                'benefits' => 'Reciting this name brings immense spiritual benefits and closeness to Allah.',
                'slug' => Str::slug('Ash-Shahid'),
            ],
            [
                'number' => 51,
                'arabic' => 'الْحَقُّ',
                'transliteration' => 'Al-Haqq',
                'meaning_english' => 'The Truth',
                'meaning_urdu' => 'سچا',
                'benefits' => 'Reciting this name brings immense spiritual benefits and closeness to Allah.',
                'slug' => Str::slug('Al-Haqq'),
            ],
            [
                'number' => 52,
                'arabic' => 'الْوَكِيلُ',
                'transliteration' => 'Al-Wakil',
                'meaning_english' => 'The Trustee',
                'meaning_urdu' => 'کارساز',
                'benefits' => 'Reciting this name brings immense spiritual benefits and closeness to Allah.',
                'slug' => Str::slug('Al-Wakil'),
            ],
            [
                'number' => 53,
                'arabic' => 'الْقَوِيُّ',
                'transliteration' => 'Al-Qawi',
                'meaning_english' => 'The Possessor of All Strength',
                'meaning_urdu' => 'زور آور',
                'benefits' => 'Reciting this name brings immense spiritual benefits and closeness to Allah.',
                'slug' => Str::slug('Al-Qawi'),
            ],
            [
                'number' => 54,
                'arabic' => 'الْمَتِينُ',
                'transliteration' => 'Al-Matin',
                'meaning_english' => 'The Forceful One',
                'meaning_urdu' => 'مضبوط',
                'benefits' => 'Reciting this name brings immense spiritual benefits and closeness to Allah.',
                'slug' => Str::slug('Al-Matin'),
            ],
            [
                'number' => 55,
                'arabic' => 'الْوَلِيُّ',
                'transliteration' => 'Al-Wali',
                'meaning_english' => 'The Governor',
                'meaning_urdu' => 'حمایتی',
                'benefits' => 'Reciting this name brings immense spiritual benefits and closeness to Allah.',
                'slug' => Str::slug('Al-Wali'),
            ],
            [
                'number' => 56,
                'arabic' => 'الْحَمِيدُ',
                'transliteration' => 'Al-Hamid',
                'meaning_english' => 'The Praised One',
                'meaning_urdu' => 'تعریف کے لائق',
                'benefits' => 'Reciting this name brings immense spiritual benefits and closeness to Allah.',
                'slug' => Str::slug('Al-Hamid'),
            ],
            [
                'number' => 57,
                'arabic' => 'الْمُحْصِي',
                'transliteration' => 'Al-Muhsi',
                'meaning_english' => 'The Appraiser',
                'meaning_urdu' => 'شمار کرنے والا',
                'benefits' => 'Reciting this name brings immense spiritual benefits and closeness to Allah.',
                'slug' => Str::slug('Al-Muhsi'),
            ],
            [
                'number' => 58,
                'arabic' => 'الْمُبْدِئُ',
                'transliteration' => 'Al-Mubdi',
                'meaning_english' => 'The Originator',
                'meaning_urdu' => 'پہلی بار پیدا کرنے والا',
                'benefits' => 'Reciting this name brings immense spiritual benefits and closeness to Allah.',
                'slug' => Str::slug('Al-Mubdi'),
            ],
            [
                'number' => 59,
                'arabic' => 'الْمُعِيدُ',
                'transliteration' => 'Al-Mu\'id',
                'meaning_english' => 'The Restorer',
                'meaning_urdu' => 'دوبارہ پیدا کرنے والا',
                'benefits' => 'Reciting this name brings immense spiritual benefits and closeness to Allah.',
                'slug' => Str::slug('Al-Mu\'id'),
            ],
            [
                'number' => 60,
                'arabic' => 'الْمُحْيِي',
                'transliteration' => 'Al-Muhyi',
                'meaning_english' => 'The Giver of Life',
                'meaning_urdu' => 'زندگی دینے والا',
                'benefits' => 'Reciting this name brings immense spiritual benefits and closeness to Allah.',
                'slug' => Str::slug('Al-Muhyi'),
            ],
            [
                'number' => 61,
                'arabic' => 'اَلْمُمِيتُ',
                'transliteration' => 'Al-Mumit',
                'meaning_english' => 'The Taker of Life',
                'meaning_urdu' => 'موت دینے والا',
                'benefits' => 'Reciting this name brings immense spiritual benefits and closeness to Allah.',
                'slug' => Str::slug('Al-Mumit'),
            ],
            [
                'number' => 62,
                'arabic' => 'الْحَيُّ',
                'transliteration' => 'Al-Hayy',
                'meaning_english' => 'The Ever Living One',
                'meaning_urdu' => 'ہمیشہ زندہ رہنے والا',
                'benefits' => 'Reciting this name brings immense spiritual benefits and closeness to Allah.',
                'slug' => Str::slug('Al-Hayy'),
            ],
            [
                'number' => 63,
                'arabic' => 'الْقَيُّومُ',
                'transliteration' => 'Al-Qayyum',
                'meaning_english' => 'The Self-Existing One',
                'meaning_urdu' => 'قائم رکھنے والا',
                'benefits' => 'Reciting this name brings immense spiritual benefits and closeness to Allah.',
                'slug' => Str::slug('Al-Qayyum'),
            ],
            [
                'number' => 64,
                'arabic' => 'الْوَاجِدُ',
                'transliteration' => 'Al-Wajid',
                'meaning_english' => 'The Finder',
                'meaning_urdu' => 'پانے والا',
                'benefits' => 'Reciting this name brings immense spiritual benefits and closeness to Allah.',
                'slug' => Str::slug('Al-Wajid'),
            ],
            [
                'number' => 65,
                'arabic' => 'الْمَاجِدُ',
                'transliteration' => 'Al-Maajid',
                'meaning_english' => 'The Glorious',
                'meaning_urdu' => 'بزرگی والا',
                'benefits' => 'Reciting this name brings immense spiritual benefits and closeness to Allah.',
                'slug' => Str::slug('Al-Maajid'),
            ],
            [
                'number' => 66,
                'arabic' => 'الْواحِدُ',
                'transliteration' => 'Al-Wahid',
                'meaning_english' => 'The Only One',
                'meaning_urdu' => 'ایک',
                'benefits' => 'Reciting this name brings immense spiritual benefits and closeness to Allah.',
                'slug' => Str::slug('Al-Wahid'),
            ],
            [
                'number' => 67,
                'arabic' => 'اَلاَحَدُ',
                'transliteration' => 'Al-Ahad',
                'meaning_english' => 'The One',
                'meaning_urdu' => 'اکیلا',
                'benefits' => 'Reciting this name brings immense spiritual benefits and closeness to Allah.',
                'slug' => Str::slug('Al-Ahad'),
            ],
            [
                'number' => 68,
                'arabic' => 'الصَّمَدُ',
                'transliteration' => 'As-Samad',
                'meaning_english' => 'The Satisfier of All Needs',
                'meaning_urdu' => 'بے نیاز',
                'benefits' => 'Reciting this name brings immense spiritual benefits and closeness to Allah.',
                'slug' => Str::slug('As-Samad'),
            ],
            [
                'number' => 69,
                'arabic' => 'الْقَادِرُ',
                'transliteration' => 'Al-Qadir',
                'meaning_english' => 'The All Powerful',
                'meaning_urdu' => 'قدرت والا',
                'benefits' => 'Reciting this name brings immense spiritual benefits and closeness to Allah.',
                'slug' => Str::slug('Al-Qadir'),
            ],
            [
                'number' => 70,
                'arabic' => 'الْمُقْتَدِرُ',
                'transliteration' => 'Al-Muqtadir',
                'meaning_english' => 'The Creator of All Power',
                'meaning_urdu' => 'کامل قدرت والا',
                'benefits' => 'Reciting this name brings immense spiritual benefits and closeness to Allah.',
                'slug' => Str::slug('Al-Muqtadir'),
            ],
            [
                'number' => 71,
                'arabic' => 'الْمُقَدِّمُ',
                'transliteration' => 'Al-Muqaddim',
                'meaning_english' => 'The Expediter',
                'meaning_urdu' => 'آگے کرنے والا',
                'benefits' => 'Reciting this name brings immense spiritual benefits and closeness to Allah.',
                'slug' => Str::slug('Al-Muqaddim'),
            ],
            [
                'number' => 72,
                'arabic' => 'الْمُؤَخِّرُ',
                'transliteration' => 'Al-Mu\'akhkhir',
                'meaning_english' => 'The Delayer',
                'meaning_urdu' => 'پیچھے کرنے والا',
                'benefits' => 'Reciting this name brings immense spiritual benefits and closeness to Allah.',
                'slug' => Str::slug('Al-Mu\'akhkhir'),
            ],
            [
                'number' => 73,
                'arabic' => 'الأوَّلُ',
                'transliteration' => 'Al-Awwal',
                'meaning_english' => 'The First',
                'meaning_urdu' => 'سب سے پہلا',
                'benefits' => 'Reciting this name brings immense spiritual benefits and closeness to Allah.',
                'slug' => Str::slug('Al-Awwal'),
            ],
            [
                'number' => 74,
                'arabic' => 'الآخِرُ',
                'transliteration' => 'Al-Akhir',
                'meaning_english' => 'The Last',
                'meaning_urdu' => 'سب سے آخری',
                'benefits' => 'Reciting this name brings immense spiritual benefits and closeness to Allah.',
                'slug' => Str::slug('Al-Akhir'),
            ],
            [
                'number' => 75,
                'arabic' => 'الظَّاهِرُ',
                'transliteration' => 'Az-Zahir',
                'meaning_english' => 'The Manifest One',
                'meaning_urdu' => 'ظاہر',
                'benefits' => 'Reciting this name brings immense spiritual benefits and closeness to Allah.',
                'slug' => Str::slug('Az-Zahir'),
            ],
            [
                'number' => 76,
                'arabic' => 'الْبَاطِنُ',
                'transliteration' => 'Al-Batin',
                'meaning_english' => 'The Hidden One',
                'meaning_urdu' => 'چھپا ہوا',
                'benefits' => 'Reciting this name brings immense spiritual benefits and closeness to Allah.',
                'slug' => Str::slug('Al-Batin'),
            ],
            [
                'number' => 77,
                'arabic' => 'الْوَالِي',
                'transliteration' => 'Al-Waali',
                'meaning_english' => 'The Protecting Friend',
                'meaning_urdu' => 'مالک',
                'benefits' => 'Reciting this name brings immense spiritual benefits and closeness to Allah.',
                'slug' => Str::slug('Al-Waali'),
            ],
            [
                'number' => 78,
                'arabic' => 'الْمُتَعَالِي',
                'transliteration' => 'Al-Muta\'ali',
                'meaning_english' => 'The Supreme One',
                'meaning_urdu' => 'بہت بلند',
                'benefits' => 'Reciting this name brings immense spiritual benefits and closeness to Allah.',
                'slug' => Str::slug('Al-Muta\'ali'),
            ],
            [
                'number' => 79,
                'arabic' => 'الْبَرُّ',
                'transliteration' => 'Al-Barr',
                'meaning_english' => 'The Doer of Good',
                'meaning_urdu' => 'بھلائی کرنے والا',
                'benefits' => 'Reciting this name brings immense spiritual benefits and closeness to Allah.',
                'slug' => Str::slug('Al-Barr'),
            ],
            [
                'number' => 80,
                'arabic' => 'التَّوَابُ',
                'transliteration' => 'At-Tawwab',
                'meaning_english' => 'The Guide to Repentance',
                'meaning_urdu' => 'توبہ قبول کرنے والا',
                'benefits' => 'Reciting this name brings immense spiritual benefits and closeness to Allah.',
                'slug' => Str::slug('At-Tawwab'),
            ],
            [
                'number' => 81,
                'arabic' => 'الْمُنْتَقِمُ',
                'transliteration' => 'Al-Muntaqim',
                'meaning_english' => 'The Avenger',
                'meaning_urdu' => 'انتقام لینے والا',
                'benefits' => 'Reciting this name brings immense spiritual benefits and closeness to Allah.',
                'slug' => Str::slug('Al-Muntaqim'),
            ],
            [
                'number' => 82,
                'arabic' => 'العَفُوُّ',
                'transliteration' => 'Al-\'Afuww',
                'meaning_english' => 'The Forgiver',
                'meaning_urdu' => 'معاف کرنے والا',
                'benefits' => 'Reciting this name brings immense spiritual benefits and closeness to Allah.',
                'slug' => Str::slug('Al-\'Afuww'),
            ],
            [
                'number' => 83,
                'arabic' => 'الرَّؤُوفُ',
                'transliteration' => 'Ar-Ra\'uf',
                'meaning_english' => 'The Clement',
                'meaning_urdu' => 'بہت مہربان',
                'benefits' => 'Reciting this name brings immense spiritual benefits and closeness to Allah.',
                'slug' => Str::slug('Ar-Ra\'uf'),
            ],
            [
                'number' => 84,
                'arabic' => 'مَالِكُ ٱلْمُلْكُ',
                'transliteration' => 'Malik-al-Mulk',
                'meaning_english' => 'The Owner of All',
                'meaning_urdu' => 'بادشاہیوں کا مالک',
                'benefits' => 'Reciting this name brings immense spiritual benefits and closeness to Allah.',
                'slug' => Str::slug('Malik-al-Mulk'),
            ],
            [
                'number' => 85,
                'arabic' => 'ذُو ٱلْجَلَٰلِ وَٱلْإِكْرَامُ',
                'transliteration' => 'Dhu-al-Jalal wa-al-Ikram',
                'meaning_english' => 'The Lord of Majesty and Bounty',
                'meaning_urdu' => 'جلال اور انعام والا',
                'benefits' => 'Reciting this name brings immense spiritual benefits and closeness to Allah.',
                'slug' => Str::slug('Dhu-al-Jalal wa-al-Ikram'),
            ],
            [
                'number' => 86,
                'arabic' => 'الْمُقْسِطُ',
                'transliteration' => 'Al-Muqsit',
                'meaning_english' => 'The Equitable One',
                'meaning_urdu' => 'انصاف کرنے والا',
                'benefits' => 'Reciting this name brings immense spiritual benefits and closeness to Allah.',
                'slug' => Str::slug('Al-Muqsit'),
            ],
            [
                'number' => 87,
                'arabic' => 'الْجَامِعُ',
                'transliteration' => 'Al-Jami',
                'meaning_english' => 'The Gatherer',
                'meaning_urdu' => 'جمع کرنے والا',
                'benefits' => 'Reciting this name brings immense spiritual benefits and closeness to Allah.',
                'slug' => Str::slug('Al-Jami'),
            ],
            [
                'number' => 88,
                'arabic' => 'الْغَنِيُّ',
                'transliteration' => 'Al-Ghani',
                'meaning_english' => 'The Rich One',
                'meaning_urdu' => 'بے پرواہ',
                'benefits' => 'Reciting this name brings immense spiritual benefits and closeness to Allah.',
                'slug' => Str::slug('Al-Ghani'),
            ],
            [
                'number' => 89,
                'arabic' => 'الْمُغْنِي',
                'transliteration' => 'Al-Mughni',
                'meaning_english' => 'The Enricher',
                'meaning_urdu' => 'غنی کرنے والا',
                'benefits' => 'Reciting this name brings immense spiritual benefits and closeness to Allah.',
                'slug' => Str::slug('Al-Mughni'),
            ],
            [
                'number' => 90,
                'arabic' => 'اَلْمَانِعُ',
                'transliteration' => 'Al-Mani\'',
                'meaning_english' => 'The Preventer of Harm',
                'meaning_urdu' => 'روکنے والا',
                'benefits' => 'Reciting this name brings immense spiritual benefits and closeness to Allah.',
                'slug' => Str::slug('Al-Mani\''),
            ],
            [
                'number' => 91,
                'arabic' => 'الضَّارَّ',
                'transliteration' => 'Ad-Darr',
                'meaning_english' => 'The Creator of The Harmful',
                'meaning_urdu' => 'نقصان پہنچانے والا',
                'benefits' => 'Reciting this name brings immense spiritual benefits and closeness to Allah.',
                'slug' => Str::slug('Ad-Darr'),
            ],
            [
                'number' => 92,
                'arabic' => 'النَّافِعُ',
                'transliteration' => 'An-Nafi',
                'meaning_english' => 'The Creator of Good',
                'meaning_urdu' => 'نفع پہنچانے والا',
                'benefits' => 'Reciting this name brings immense spiritual benefits and closeness to Allah.',
                'slug' => Str::slug('An-Nafi'),
            ],
            [
                'number' => 93,
                'arabic' => 'النُّورُ',
                'transliteration' => 'An-Nur',
                'meaning_english' => 'The Light',
                'meaning_urdu' => 'روشن کرنے والا',
                'benefits' => 'Reciting this name brings immense spiritual benefits and closeness to Allah.',
                'slug' => Str::slug('An-Nur'),
            ],
            [
                'number' => 94,
                'arabic' => 'الْهَادِي',
                'transliteration' => 'Al-Hadi',
                'meaning_english' => 'The Guide',
                'meaning_urdu' => 'ہدایت دینے والا',
                'benefits' => 'Reciting this name brings immense spiritual benefits and closeness to Allah.',
                'slug' => Str::slug('Al-Hadi'),
            ],
            [
                'number' => 95,
                'arabic' => 'الْبَدِيعُ',
                'transliteration' => 'Al-Badi',
                'meaning_english' => 'The Originator',
                'meaning_urdu' => 'نئی طرح پیدا کرنے والا',
                'benefits' => 'Reciting this name brings immense spiritual benefits and closeness to Allah.',
                'slug' => Str::slug('Al-Badi'),
            ],
            [
                'number' => 96,
                'arabic' => 'اَلْبَاقِي',
                'transliteration' => 'Al-Baqi',
                'meaning_english' => 'The Everlasting One',
                'meaning_urdu' => 'ہمیشہ رہنے والا',
                'benefits' => 'Reciting this name brings immense spiritual benefits and closeness to Allah.',
                'slug' => Str::slug('Al-Baqi'),
            ],
            [
                'number' => 97,
                'arabic' => 'الْوَارِثُ',
                'transliteration' => 'Al-Warith',
                'meaning_english' => 'The Inheritor of All',
                'meaning_urdu' => 'سب کا وارث',
                'benefits' => 'Reciting this name brings immense spiritual benefits and closeness to Allah.',
                'slug' => Str::slug('Al-Warith'),
            ],
            [
                'number' => 98,
                'arabic' => 'الرَّشِيدُ',
                'transliteration' => 'Ar-Rashid',
                'meaning_english' => 'The Righteous Teacher',
                'meaning_urdu' => 'ہدایت دینے والا',
                'benefits' => 'Reciting this name brings immense spiritual benefits and closeness to Allah.',
                'slug' => Str::slug('Ar-Rashid'),
            ],
            [
                'number' => 99,
                'arabic' => 'الصَّبُورُ',
                'transliteration' => 'As-Sabur',
                'meaning_english' => 'The Patient One',
                'meaning_urdu' => 'صبر کرنے والا',
                'benefits' => 'Reciting this name brings immense spiritual benefits and closeness to Allah.',
                'slug' => Str::slug('As-Sabur'),
            ],
        ];

        foreach ($names as $name) {
            AllahName::create($name);
        }
    }
}
