<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DreamSymbolSeeder extends Seeder
{
    public function run(): void
    {
        $symbols = [
            ['symbol_urdu' => 'پانی', 'symbol_english' => 'Water', 'interpretation_urdu' => 'صاف پانی دیکھنا علم، رزق اور برکت کی نشانی ہے۔ گندا پانی فتنے اور مشکلات کی علامت ہے۔', 'interpretation_english' => 'Clean water represents knowledge, sustenance and blessings. Dirty water indicates trials and difficulties.', 'scholar_reference' => 'Ibn Sirin', 'is_good_dream' => 1, 'slug' => 'water-pani'],
            ['symbol_urdu' => 'سانپ', 'symbol_english' => 'Snake', 'interpretation_urdu' => 'سانپ دیکھنا دشمن کی نشانی ہے۔ سانپ مارنا دشمن پر غلبہ پانا ہے۔ سانپ کا ڈسنا نقصان کی علامت ہے۔', 'interpretation_english' => 'Seeing a snake indicates an enemy. Killing a snake means overcoming the enemy.', 'scholar_reference' => 'Ibn Sirin', 'is_good_dream' => 0, 'slug' => 'snake-saanp'],
            ['symbol_urdu' => 'اُڑنا', 'symbol_english' => 'Flying', 'interpretation_urdu' => 'خواب میں اُڑنا سفر کی علامت ہے۔ اگر بلند اُڑے تو بلند مقام حاصل ہوگا۔', 'interpretation_english' => 'Flying in a dream symbolizes travel and elevation in status.', 'scholar_reference' => 'Ibn Sirin', 'is_good_dream' => 1, 'slug' => 'flying-urna'],
            ['symbol_urdu' => 'دانت گرنا', 'symbol_english' => 'Teeth Falling', 'interpretation_urdu' => 'دانت گرنا عمر لمبی ہونے یا رشتہ داروں سے متعلق خبر کی نشانی ہے۔ اوپر کے دانت مردانہ رشتے اور نیچے کے دانت عورتوں کے رشتے ہیں۔', 'interpretation_english' => 'Teeth falling indicates news about relatives. Upper teeth represent male relatives, lower teeth female relatives.', 'scholar_reference' => 'Ibn Sirin', 'is_good_dream' => null, 'slug' => 'teeth-falling-dant'],
            ['symbol_urdu' => 'دودھ', 'symbol_english' => 'Milk', 'interpretation_urdu' => 'دودھ پینا فطرت اور علم کی نشانی ہے۔ نبی ﷺ نے معراج کی رات دودھ چنا جو فطرت کی علامت ہے۔', 'interpretation_english' => 'Drinking milk represents natural disposition (fitrah) and knowledge.', 'scholar_reference' => 'Ibn Sirin / Hadith', 'is_good_dream' => 1, 'slug' => 'milk-doodh'],
            ['symbol_urdu' => 'مسجد', 'symbol_english' => 'Mosque', 'interpretation_urdu' => 'مسجد دیکھنا ایمان، علم اور ہدایت کی نشانی ہے۔ مسجد بنانا نیک عمل کی علامت ہے۔', 'interpretation_english' => 'Seeing a mosque indicates faith, knowledge and guidance.', 'scholar_reference' => 'Ibn Sirin', 'is_good_dream' => 1, 'slug' => 'mosque-masjid'],
            ['symbol_urdu' => 'قرآن پاک', 'symbol_english' => 'Quran', 'interpretation_urdu' => 'قرآن پاک دیکھنا یا پڑھنا ہدایت، برکت اور اللہ کے قرب کی نشانی ہے۔', 'interpretation_english' => 'Seeing or reading the Quran indicates guidance, blessings and closeness to Allah.', 'scholar_reference' => 'Ibn Sirin', 'is_good_dream' => 1, 'slug' => 'quran-pak'],
            ['symbol_urdu' => 'آگ', 'symbol_english' => 'Fire', 'interpretation_urdu' => 'آگ دیکھنا فتنے اور مشکلات کی علامت ہے۔ آگ سے بچنا فتنوں سے نجات ہے۔ دوزخ کی آگ دیکھنا توبہ کی نشانی ہے۔', 'interpretation_english' => 'Fire represents trials and tribulations. Escaping fire means deliverance from trials.', 'scholar_reference' => 'Ibn Sirin', 'is_good_dream' => 0, 'slug' => 'fire-aag'],
            ['symbol_urdu' => 'بارش', 'symbol_english' => 'Rain', 'interpretation_urdu' => 'بارش رحمت الٰہی اور رزق کی نشانی ہے۔ ہلکی بارش رحمت ہے اور سیلابی بارش عذاب کی علامت ہو سکتی ہے۔', 'interpretation_english' => 'Rain symbolizes divine mercy and sustenance. Light rain is mercy, floods may indicate punishment.', 'scholar_reference' => 'Ibn Sirin', 'is_good_dream' => 1, 'slug' => 'rain-barish'],
            ['symbol_urdu' => 'شیر (Lion)', 'symbol_english' => 'Lion', 'interpretation_urdu' => 'شیر دیکھنا طاقتور حکمران یا دشمن کی علامت ہے۔ شیر کو زیر کرنا دشمن پر غلبہ ہے۔', 'interpretation_english' => 'A lion represents a powerful ruler or enemy. Subduing a lion means victory.', 'scholar_reference' => 'Ibn Sirin', 'is_good_dream' => null, 'slug' => 'lion-sher'],
            ['symbol_urdu' => 'شہد', 'symbol_english' => 'Honey', 'interpretation_urdu' => 'شہد دیکھنا قرآن، علم اور حلال رزق کی نشانی ہے۔ شہد کھانا شفا کی علامت ہے۔', 'interpretation_english' => 'Honey represents Quran, knowledge and lawful earnings. Eating honey symbolizes healing.', 'scholar_reference' => 'Ibn Sirin', 'is_good_dream' => 1, 'slug' => 'honey-shehad'],
            ['symbol_urdu' => 'کعبہ', 'symbol_english' => 'Kaaba', 'interpretation_urdu' => 'کعبہ شریف دیکھنا حج یا عمرے کی نشانی ہے۔ طواف کرنا عبادت اور ایمان کی مضبوطی ہے۔', 'interpretation_english' => 'Seeing the Kaaba indicates Hajj or Umrah. Performing Tawaf means strengthening of faith.', 'scholar_reference' => 'Ibn Sirin', 'is_good_dream' => 1, 'slug' => 'kaaba-sharif'],
            ['symbol_urdu' => 'چاند', 'symbol_english' => 'Moon', 'interpretation_urdu' => 'چاند دیکھنا عالم، وزیر یا خوبصورت عورت کی نشانی ہے۔ پورا چاند کامیابی اور عزت ہے۔', 'interpretation_english' => 'The moon represents a scholar, minister or beauty. Full moon means success and honor.', 'scholar_reference' => 'Ibn Sirin', 'is_good_dream' => 1, 'slug' => 'moon-chand'],
            ['symbol_urdu' => 'سورج', 'symbol_english' => 'Sun', 'interpretation_urdu' => 'سورج بادشاہ یا حکمران کی علامت ہے۔ سورج طلوع ہوتا دیکھنا ترقی اور غلبے کی نشانی ہے۔', 'interpretation_english' => 'The sun represents a king or ruler. Seeing sunrise indicates progress and dominance.', 'scholar_reference' => 'Ibn Sirin', 'is_good_dream' => 1, 'slug' => 'sun-suraj'],
            ['symbol_urdu' => 'مردہ شخص', 'symbol_english' => 'Dead Person', 'interpretation_urdu' => 'فوت شدہ شخص کو خوش دیکھنا اس کی اچھی حالت کی نشانی ہے۔ اگر وہ کچھ دے تو رزق ملے گا۔', 'interpretation_english' => 'Seeing a deceased person happy indicates their good state. If they give something, it means sustenance.', 'scholar_reference' => 'Ibn Sirin', 'is_good_dream' => 1, 'slug' => 'dead-person-murda'],
            ['symbol_urdu' => 'گھوڑا', 'symbol_english' => 'Horse', 'interpretation_urdu' => 'گھوڑا دیکھنا عزت، مال اور سفر کی نشانی ہے۔ سفید گھوڑا بہتر ہے۔', 'interpretation_english' => 'A horse indicates honor, wealth and travel. A white horse is especially favorable.', 'scholar_reference' => 'Ibn Sirin', 'is_good_dream' => 1, 'slug' => 'horse-ghora'],
            ['symbol_urdu' => 'سمندر', 'symbol_english' => 'Sea/Ocean', 'interpretation_urdu' => 'سمندر دیکھنا بادشاہ یا بڑے عالم کی علامت ہے۔ سمندر میں ڈوبنا مشکلات میں پڑنا ہے۔', 'interpretation_english' => 'The sea represents a powerful ruler or scholar. Drowning indicates falling into difficulties.', 'scholar_reference' => 'Ibn Sirin', 'is_good_dream' => null, 'slug' => 'sea-samandar'],
            ['symbol_urdu' => 'نبی ﷺ کو دیکھنا', 'symbol_english' => 'Seeing Prophet Muhammad ﷺ', 'interpretation_urdu' => 'نبی ﷺ کو خواب میں دیکھنا سچا خواب ہے کیونکہ شیطان آپ ﷺ کی شکل نہیں لے سکتا۔ یہ بہترین خواب ہے۔', 'interpretation_english' => 'Seeing Prophet Muhammad ﷺ in a dream is a true dream as Satan cannot take his form. It is the best dream.', 'scholar_reference' => 'Sahih Bukhari 6993', 'is_good_dream' => 1, 'slug' => 'seeing-prophet-muhammad'],
            ['symbol_urdu' => 'درخت', 'symbol_english' => 'Tree', 'interpretation_urdu' => 'ہرا درخت نیک آدمی اور اچھے عمل کی نشانی ہے۔ خشک درخت منافق کی علامت ہے۔ کھجور کا درخت مومن ہے۔', 'interpretation_english' => 'A green tree represents a righteous person. A dry tree represents a hypocrite. A palm tree is a believer.', 'scholar_reference' => 'Ibn Sirin / Hadith', 'is_good_dream' => 1, 'slug' => 'tree-darakht'],
            ['symbol_urdu' => 'انگوٹھی', 'symbol_english' => 'Ring', 'interpretation_urdu' => 'انگوٹھی دیکھنا اختیار اور حکومت کی نشانی ہے۔ سونے کی انگوٹھی مردوں کے لیے مکروہ ہے۔', 'interpretation_english' => 'A ring represents authority and power. Gold ring for men is disliked in Islam.', 'scholar_reference' => 'Ibn Sirin', 'is_good_dream' => null, 'slug' => 'ring-anguthi'],
            ['symbol_urdu' => 'خون', 'symbol_english' => 'Blood', 'interpretation_urdu' => 'خون دیکھنا حرام مال یا گناہ کی علامت ہے۔ خون بہنا مال خرچ ہونا ہے۔', 'interpretation_english' => 'Blood represents unlawful wealth or sin. Bleeding indicates spending wealth.', 'scholar_reference' => 'Ibn Sirin', 'is_good_dream' => 0, 'slug' => 'blood-khoon'],
            ['symbol_urdu' => 'پہاڑ', 'symbol_english' => 'Mountain', 'interpretation_urdu' => 'پہاڑ دیکھنا ثابت قدمی اور طاقت کی نشانی ہے۔ پہاڑ پر چڑھنا ترقی اور کامیابی ہے۔', 'interpretation_english' => 'Mountains represent steadfastness and strength. Climbing a mountain indicates success.', 'scholar_reference' => 'Ibn Sirin', 'is_good_dream' => 1, 'slug' => 'mountain-pahar'],
            ['symbol_urdu' => 'تلوار', 'symbol_english' => 'Sword', 'interpretation_urdu' => 'تلوار دیکھنا زبان کی تیزی اور حجت کی علامت ہے۔ تلوار سے لڑنا مناظرہ اور بحث ہے۔', 'interpretation_english' => 'A sword represents sharp tongue and argument. Fighting with a sword means debate and argument.', 'scholar_reference' => 'Ibn Sirin', 'is_good_dream' => null, 'slug' => 'sword-talwar'],
            ['symbol_urdu' => 'سفید کپڑے', 'symbol_english' => 'White Clothes', 'interpretation_urdu' => 'سفید کپڑے پہننا پاکیزگی، نیکی اور اچھی حالت کی نشانی ہے۔ نبی ﷺ نے سفید کپڑے پسند فرمائے۔', 'interpretation_english' => 'White clothes represent purity, righteousness and a good state. The Prophet ﷺ preferred white garments.', 'scholar_reference' => 'Ibn Sirin / Hadith', 'is_good_dream' => 1, 'slug' => 'white-clothes-safed'],
            ['symbol_urdu' => 'بلی', 'symbol_english' => 'Cat', 'interpretation_urdu' => 'بلی دیکھنا چور یا خادم کی نشانی ہے۔ بلی کا کاٹنا دھوکے کی علامت ہے۔', 'interpretation_english' => 'A cat represents a thief or servant. A cat biting indicates deception.', 'scholar_reference' => 'Ibn Sirin', 'is_good_dream' => null, 'slug' => 'cat-billi'],
            ['symbol_urdu' => 'پرندہ', 'symbol_english' => 'Bird', 'interpretation_urdu' => 'پرندہ دیکھنا خوشخبری کی نشانی ہے۔ سبز پرندہ جنت کی نشانی ہے۔ پرندہ اُڑنا سفر ہے۔', 'interpretation_english' => 'A bird represents good news. A green bird symbolizes paradise. A flying bird means travel.', 'scholar_reference' => 'Ibn Sirin', 'is_good_dream' => 1, 'slug' => 'bird-parinda'],
            ['symbol_urdu' => 'کنواں', 'symbol_english' => 'Well', 'interpretation_urdu' => 'کنواں دیکھنا علم اور مال کی نشانی ہے۔ کنویں سے پانی نکالنا رزق حاصل کرنا ہے۔', 'interpretation_english' => 'A well represents knowledge and wealth. Drawing water from a well means earning sustenance.', 'scholar_reference' => 'Ibn Sirin', 'is_good_dream' => 1, 'slug' => 'well-kunwan'],
            ['symbol_urdu' => 'چابی', 'symbol_english' => 'Key', 'interpretation_urdu' => 'چابی دیکھنا مشکل حل ہونے اور نئے دروازے کھلنے کی نشانی ہے۔ سونے کی چابی علم کی کنجی ہے۔', 'interpretation_english' => 'A key represents solving problems and new opportunities. A golden key is the key to knowledge.', 'scholar_reference' => 'Ibn Sirin', 'is_good_dream' => 1, 'slug' => 'key-chabi'],
            ['symbol_urdu' => 'روٹی', 'symbol_english' => 'Bread', 'interpretation_urdu' => 'روٹی دیکھنا رزق اور معاش کی نشانی ہے۔ تازہ روٹی اچھا رزق ہے اور باسی روٹی پرانا مال ہے۔', 'interpretation_english' => 'Bread represents livelihood. Fresh bread is good sustenance, stale bread is old wealth.', 'scholar_reference' => 'Ibn Sirin', 'is_good_dream' => 1, 'slug' => 'bread-roti'],
        ];

        foreach ($symbols as $s) {
            DB::table('dream_symbols')->updateOrInsert(
                ['slug' => $s['slug']],
                array_merge($s, ['created_at' => now(), 'updated_at' => now()])
            );
        }

        $this->command->info('✅ 30 dream symbols seeded successfully.');
    }
}
