<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class WazaifSeeder extends Seeder
{
    public function run(): void
    {
        $wazaif = [
            ['title_urdu' => 'رزق کی وسعت کا وظیفہ', 'title_english' => 'Wazifa for Rizq', 'arabic_text' => 'يَا رَزَّاقُ', 'urdu_text' => 'فجر کی نماز کے بعد ١٠٨ مرتبہ "یا رزاق" پڑھیں۔ اللہ تعالیٰ رزق میں وسعت فرمائیں گے۔', 'purpose' => 'رزق', 'reference' => 'اسماء الحسنی — القرآن ٥١:٥٨', 'method' => 'فجر کے بعد ١٠٨ مرتبہ پڑھیں', 'slug' => 'wazifa-for-rizq', 'is_authentic' => 1],
            ['title_urdu' => 'شفا کا وظیفہ', 'title_english' => 'Wazifa for Shifa (Healing)', 'arabic_text' => 'اللَّهُمَّ رَبَّ النَّاسِ أَذْهِبِ الْبَأْسَ اشْفِ أَنْتَ الشَّافِي لاَ شِفَاءَ إِلاَّ شِفَاؤُكَ شِفَاءً لاَ يُغَادِرُ سَقَمًا', 'urdu_text' => 'بیمار پر ہاتھ رکھ کر ٧ مرتبہ پڑھیں۔ یہ دعا نبی ﷺ سے ثابت ہے۔', 'purpose' => 'شفا', 'reference' => 'صحیح بخاری ٥٦٧٥', 'method' => 'بیمار کے سر پر ہاتھ رکھ کر ٧ بار پڑھیں', 'slug' => 'wazifa-for-shifa', 'is_authentic' => 1, 'scholar_verified' => 1],
            ['title_urdu' => 'شادی کا وظیفہ', 'title_english' => 'Wazifa for Marriage', 'arabic_text' => 'رَبِّ إِنِّي لِمَا أَنزَلْتَ إِلَيَّ مِنْ خَيْرٍ فَقِيرٌ', 'urdu_text' => 'سورہ القصص آیت ٢٤ — حضرت موسیٰ علیہ السلام کی دعا۔ روزانہ ١١ مرتبہ پڑھیں۔', 'purpose' => 'شادی', 'reference' => 'سورہ القصص ٢٨:٢٤', 'method' => 'نماز کے بعد ١١ مرتبہ پڑھیں', 'slug' => 'wazifa-for-marriage', 'is_authentic' => 1],
            ['title_urdu' => 'امتحان میں کامیابی کا وظیفہ', 'title_english' => 'Wazifa for Exam Success', 'arabic_text' => 'رَبِّ زِدْنِي عِلْمًا', 'urdu_text' => 'اے میرے رب! میرے علم میں اضافہ فرما۔ امتحان سے پہلے ٢١ مرتبہ پڑھیں۔', 'purpose' => 'امتحان', 'reference' => 'سورہ طہ ٢٠:١١٤', 'method' => 'امتحان سے پہلے ٢١ مرتبہ', 'slug' => 'wazifa-for-exam-success', 'is_authentic' => 1],
            ['title_urdu' => 'قرض سے نجات کا وظیفہ', 'title_english' => 'Wazifa for Debt Relief', 'arabic_text' => 'اللَّهُمَّ اكْفِنِي بِحَلاَلِكَ عَنْ حَرَامِكَ وَأَغْنِنِي بِفَضْلِكَ عَمَّنْ سِوَاكَ', 'urdu_text' => 'یہ دعا نبی ﷺ نے حضرت علی رضی اللہ عنہ کو سکھائی جب وہ قرض میں ڈوبے ہوئے تھے۔', 'purpose' => 'قرض', 'reference' => 'جامع ترمذی ٣٥٦٣', 'method' => 'نماز عشاء کے بعد ٧ مرتبہ', 'slug' => 'wazifa-for-debt-relief', 'is_authentic' => 1, 'scholar_verified' => 1],
            ['title_urdu' => 'پریشانی دور کرنے کا وظیفہ', 'title_english' => 'Wazifa for Removing Worries', 'arabic_text' => 'لَا إِلَٰهَ إِلَّا أَنتَ سُبْحَانَكَ إِنِّي كُنتُ مِنَ الظَّالِمِينَ', 'urdu_text' => 'دعائے یونس — ہر قسم کی پریشانی اور تنگی سے نجات کا ذریعہ ہے۔', 'purpose' => 'پریشانی', 'reference' => 'سورہ الانبیاء ٢١:٨٧', 'method' => 'کسی بھی وقت ١٢٥ مرتبہ پڑھیں', 'slug' => 'wazifa-for-removing-worries', 'is_authentic' => 1, 'scholar_verified' => 1],
            ['title_urdu' => 'نظربد سے حفاظت', 'title_english' => 'Protection from Evil Eye', 'arabic_text' => 'أَعُوذُ بِكَلِمَاتِ اللهِ التَّامَّةِ مِنْ كُلِّ شَيْطَانٍ وَهَامَّةٍ وَمِنْ كُلِّ عَيْنٍ لاَمَّةٍ', 'urdu_text' => 'نبی ﷺ حسن و حسین رضی اللہ عنہما کو اس دعا سے دم کیا کرتے تھے۔', 'purpose' => 'نظربد', 'reference' => 'صحیح بخاری ٣٣٧١', 'method' => 'صبح شام بچوں پر دم کریں', 'slug' => 'protection-from-evil-eye', 'is_authentic' => 1, 'scholar_verified' => 1],
            ['title_urdu' => 'اولاد کی خواہش', 'title_english' => 'Wazifa for Children', 'arabic_text' => 'رَبِّ هَبْ لِي مِنَ الصَّالِحِينَ', 'urdu_text' => 'حضرت ابراہیم علیہ السلام کی دعا — اللہ سے نیک اولاد مانگنے کے لیے۔', 'purpose' => 'اولاد', 'reference' => 'سورہ الصافات ٣٧:١٠٠', 'method' => 'تہجد کے بعد ٤١ مرتبہ', 'slug' => 'wazifa-for-children', 'is_authentic' => 1],
            ['title_urdu' => 'استخارہ کی دعا', 'title_english' => 'Istikhara Dua', 'arabic_text' => 'اللَّهُمَّ إِنِّي أَسْتَخِيرُكَ بِعِلْمِكَ وَأَسْتَقْدِرُكَ بِقُدْرَتِكَ وَأَسْأَلُكَ مِنْ فَضْلِكَ الْعَظِيمِ', 'urdu_text' => 'کسی بھی اہم فیصلے سے پہلے ٢ رکعت نفل پڑھ کر یہ دعا مانگیں۔', 'purpose' => 'فیصلہ', 'reference' => 'صحیح بخاری ١١٦٢', 'method' => '٢ رکعت نفل کے بعد مکمل دعا پڑھیں', 'slug' => 'istikhara-dua', 'is_authentic' => 1, 'scholar_verified' => 1],
            ['title_urdu' => 'گھر کی حفاظت', 'title_english' => 'Protection of Home', 'arabic_text' => 'بِسْمِ اللَّهِ الَّذِي لَا يَضُرُّ مَعَ اسْمِهِ شَيْءٌ فِي الْأَرْضِ وَلَا فِي السَّمَاءِ وَهُوَ السَّمِيعُ الْعَلِيمُ', 'urdu_text' => 'صبح و شام ٣ مرتبہ پڑھنے سے کوئی چیز نقصان نہیں دے سکتی۔', 'purpose' => 'حفاظت', 'reference' => 'ابو داؤد ٥٠٨٨', 'method' => 'صبح و شام ٣ مرتبہ', 'slug' => 'protection-of-home', 'is_authentic' => 1, 'scholar_verified' => 1],
            ['title_urdu' => 'یادداشت بڑھانے کا وظیفہ', 'title_english' => 'Wazifa for Memory', 'arabic_text' => 'رَبِّ اشْرَحْ لِي صَدْرِي وَيَسِّرْ لِي أَمْرِي وَاحْلُلْ عُقْدَةً مِنْ لِسَانِي يَفْقَهُوا قَوْلِي', 'urdu_text' => 'حضرت موسیٰ علیہ السلام کی دعا — علم سمجھنے اور یاد رکھنے کے لیے۔', 'purpose' => 'یادداشت', 'reference' => 'سورہ طہ ٢٠:٢٥-٢٨', 'method' => 'پڑھائی سے پہلے ٧ مرتبہ', 'slug' => 'wazifa-for-memory', 'is_authentic' => 1],
            ['title_urdu' => 'نوکری کے لیے وظیفہ', 'title_english' => 'Wazifa for Job', 'arabic_text' => 'وَمَن يَتَّقِ اللَّهَ يَجْعَل لَّهُ مَخْرَجًا وَيَرْزُقْهُ مِنْ حَيْثُ لَا يَحْتَسِبُ', 'urdu_text' => 'جو اللہ سے ڈرے اللہ اس کے لیے نکلنے کا راستہ بنا دے گا اور ایسی جگہ سے رزق دے گا جہاں سے گمان بھی نہ ہو۔', 'purpose' => 'نوکری', 'reference' => 'سورہ الطلاق ٦٥:٢-٣', 'method' => 'فجر کے بعد ٤١ مرتبہ ٤٠ دن تک', 'slug' => 'wazifa-for-job', 'is_authentic' => 1],
            ['title_urdu' => 'میاں بیوی کی محبت', 'title_english' => 'Wazifa for Love Between Spouses', 'arabic_text' => 'رَبَّنَا هَبْ لَنَا مِنْ أَزْوَاجِنَا وَذُرِّيَّاتِنَا قُرَّةَ أَعْيُنٍ وَاجْعَلْنَا لِلْمُتَّقِينَ إِمَامًا', 'urdu_text' => 'اے ہمارے رب! ہمیں بیویوں اور اولاد سے آنکھوں کی ٹھنڈک عطا فرما۔', 'purpose' => 'محبت', 'reference' => 'سورہ الفرقان ٢٥:٧٤', 'method' => 'نماز تہجد میں دعا مانگیں', 'slug' => 'wazifa-for-spouse-love', 'is_authentic' => 1],
            ['title_urdu' => 'سفر کی حفاظت', 'title_english' => 'Travel Protection', 'arabic_text' => 'سُبْحَانَ الَّذِي سَخَّرَ لَنَا هَٰذَا وَمَا كُنَّا لَهُ مُقْرِنِينَ', 'urdu_text' => 'سفر شروع کرتے وقت یہ دعا پڑھیں — سواری پر بیٹھ کر۔', 'purpose' => 'سفر', 'reference' => 'سورہ الزخرف ٤٣:١٣', 'method' => 'گاڑی میں بیٹھتے ہی پڑھیں', 'slug' => 'travel-protection', 'is_authentic' => 1, 'scholar_verified' => 1],
            ['title_urdu' => 'توبہ و استغفار', 'title_english' => 'Repentance - Sayyidul Istighfar', 'arabic_text' => 'اللَّهُمَّ أَنْتَ رَبِّي لَا إِلَٰهَ إِلَّا أَنْتَ خَلَقْتَنِي وَأَنَا عَبْدُكَ', 'urdu_text' => 'سید الاستغفار — سب سے افضل استغفار۔ صبح شام پڑھنے سے جنت واجب ہو جاتی ہے۔', 'purpose' => 'توبہ', 'reference' => 'صحیح بخاری ٦٣٠٦', 'method' => 'صبح اور شام ایک ایک مرتبہ', 'slug' => 'sayyidul-istighfar', 'is_authentic' => 1, 'scholar_verified' => 1],
            ['title_urdu' => 'کاروبار میں برکت', 'title_english' => 'Barakah in Business', 'arabic_text' => 'اللَّهُمَّ إِنِّي أَسْأَلُكَ عِلْمًا نَافِعًا وَرِزْقًا طَيِّبًا وَعَمَلًا مُتَقَبَّلًا', 'urdu_text' => 'اے اللہ! مجھے نفع بخش علم، پاک رزق اور قبول ہونے والے عمل عطا فرما۔', 'purpose' => 'کاروبار', 'reference' => 'سنن ابن ماجہ ٩٢٥', 'method' => 'فجر کے بعد دعا مانگیں', 'slug' => 'barakah-in-business', 'is_authentic' => 1, 'scholar_verified' => 1],
            ['title_urdu' => 'مشکل کام آسان ہونے کا وظیفہ', 'title_english' => 'Wazifa for Ease in Difficulty', 'arabic_text' => 'اللَّهُمَّ لَا سَهْلَ إِلَّا مَا جَعَلْتَهُ سَهْلًا وَأَنْتَ تَجْعَلُ الْحَزْنَ إِذَا شِئْتَ سَهْلًا', 'urdu_text' => 'اے اللہ! کوئی چیز آسان نہیں سوائے اس کے جسے تو آسان بنا دے۔', 'purpose' => 'آسانی', 'reference' => 'صحیح ابن حبان ٩٧٤', 'method' => 'مشکل کام سے پہلے ٣ مرتبہ', 'slug' => 'wazifa-for-ease', 'is_authentic' => 1, 'scholar_verified' => 1],
            ['title_urdu' => 'آیت الکرسی کے فضائل', 'title_english' => 'Ayatul Kursi Benefits', 'arabic_text' => 'اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ', 'urdu_text' => 'ہر فرض نماز کے بعد آیت الکرسی پڑھنے سے جنت میں داخلے سے صرف موت رکاوٹ ہے۔', 'purpose' => 'حفاظت', 'reference' => 'سنن نسائی الکبری', 'method' => 'ہر نماز کے بعد ١ مرتبہ', 'slug' => 'ayatul-kursi-benefits', 'is_authentic' => 1, 'scholar_verified' => 1],
            ['title_urdu' => 'بچوں کی حفاظت کا وظیفہ', 'title_english' => 'Protection of Children', 'arabic_text' => 'أُعِيذُكُمَا بِكَلِمَاتِ اللَّهِ التَّامَّةِ مِنْ كُلِّ شَيْطَانٍ وَهَامَّةٍ وَمِنْ كُلِّ عَيْنٍ لَامَّةٍ', 'urdu_text' => 'نبی ﷺ حسن و حسین رضی اللہ عنہما پر یہ دعا پڑھا کرتے تھے۔', 'purpose' => 'بچوں کی حفاظت', 'reference' => 'صحیح بخاری ٣٣٧١', 'method' => 'بچوں کے سر پر ہاتھ رکھ کر پڑھیں', 'slug' => 'protection-of-children', 'is_authentic' => 1, 'scholar_verified' => 1],
            ['title_urdu' => 'غصہ کم کرنے کا وظیفہ', 'title_english' => 'Controlling Anger', 'arabic_text' => 'أَعُوذُ بِاللَّهِ مِنَ الشَّيْطَانِ الرَّجِيمِ', 'urdu_text' => 'غصے کی حالت میں اعوذ باللہ پڑھیں، کھڑے ہیں تو بیٹھ جائیں، بیٹھے ہیں تو لیٹ جائیں۔', 'purpose' => 'غصہ', 'reference' => 'صحیح بخاری ٦٠٤٨', 'method' => 'غصے کی حالت میں فوراً پڑھیں', 'slug' => 'controlling-anger', 'is_authentic' => 1, 'scholar_verified' => 1],
        ];

        foreach ($wazaif as $w) {
            DB::table('wazaif')->updateOrInsert(
                ['slug' => $w['slug']],
                array_merge($w, ['created_at' => now(), 'updated_at' => now()])
            );
        }

        $this->command->info('✅ 20 authentic wazaif seeded successfully.');
    }
}
